# syntax=docker/dockerfile:1
ARG NODE_IMG=node:24.4.0-alpine

FROM ${NODE_IMG} AS installer

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/cache/npm npm install --cache=/cache/npm

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
