FROM node:16-alpine as installer

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
