FROM node:18-alpine as installer

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

ENV npm_config_cache=/cache/npm
COPY package*.json ./
RUN --mount=type=cache,target=/cache/npm npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
