ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autofix_commit_msg: 'style: pre-commit fixes'

files: ^(backend/docs/|lib/python/|lib/modelscan_api/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ['-a', 'from __future__ import annotations', '-l', '120']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        name: pyupgrade 3.9
        args: ['--py39-plus']
        exclude: backend/docs/
      - id: pyupgrade
        name: pyupgrade 3.11
        args: ['--py311-plus']
        # backend/docs/ has the minimum python version 3.11
        files: backend/docs/

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args: [--config=lib/python/pyproject.toml]
        stages: [manual]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: ['--config', 'lib/python/pyproject.toml']
