name: bailo-dev

services:
  webhook-tester:
    networks:
      default:
      internal:
    image: tarampampam/webhook-tester:2.2.5
    command: serve --auto-create-sessions
    ports:
      - 8082:8080

  mailcrab:
    networks:
      default:
      internal:
    ports:
      - 1080:1080
      - 1025:1025
    image: marlonb/mailcrab:v1.6.4

  backend:
    ports:
      - 9229:9229
    volumes:
      - ./backend/src:/app/src
    build:
      target: dev

  frontend:
    volumes:
      - ./frontend:/app
    build:
      target: dev

  artefactscan:
    volumes:
      - ./lib/modelscan_api/bailo_modelscan_api:/app/bailo_modelscan_api
    build:
      target: dev

  minio:
    environment:
      MINIO_BROWSER_REDIRECT_URL: http://localhost:8080/minio/ui/
      MINIO_SERVER_URL: http://minio:9000
      MINIO_SKIP_CLIENT: yes

networks:
  debug:
    name: ${INSTANCE_NAME}_debug
