FROM node:16-alpine3.15

ARG user_id=1001

RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

# We use 'RUN' instead of 'ADD' here due to odd caching issues where 'ADD' would still
# download S2I, then check that it hasn't changed before accepting it was cached.
# 'RUN' instead caches based on text contents.
RUN mkdir /s2i && \
    wget -O s2i.tar.gz https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz && \
    tar -xvf s2i.tar.gz -C /s2i && \
    rm -rf s2i.tar.gz && \
    apk add --no-cache ca-certificates img docker shadow libc6-compat

RUN if [[ $user_id -eq 1000 ]]; then groupmod -g 1001 node && usermod -u 1001 -g 1001 node ; fi \
  && chmod u+s /usr/bin/newuidmap /usr/bin/newgidmap \
  && adduser -D -u $user_id user \
  && mkdir -p /run/user/$user_id \
  && chown -R user /run/user/$user_id /home/user \
  && chmod -R o+x /s2i \ 
  && addgroup -S certs \
  && addgroup user certs \
  && chgrp certs /etc/ssl/certs \
  && chmod 775 /etc/ssl/certs \
  && echo user:100000:65536 | tee /etc/subuid | tee /etc/subgid 


COPY package.json /home/user/app/package.json
COPY package-lock.json /home/user/app/package-lock.json

WORKDIR /home/user/app
RUN npm install

COPY --chown=user . / /home/user/app/

USER user
ENV USER user
ENV HOME /home/user
ENV XDG_RUNTIME_DIR=/run/user/$user_id

## We don't pull the image here because there's no way to turn off 
## seccomp/apparmor in a build like we can during run
# RUN img pull seldonio/seldon-core-s2i-python37:1.10.0

EXPOSE 3000
#CMD ["npm", "run", "dev"]
CMD ./scripts/run_app_dev.sh
