FROM gcr.io/kaniko-project/executor as executor

FROM node:16-alpine

WORKDIR /app

# Install Kaniko
COPY --from=executor /kaniko /kaniko
COPY --from=executor /kaniko/ssl/certs/ /kaniko/ssl/certs/
COPY --from=executor /etc/nsswitch.conf /etc/nsswitch.conf

ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV DOCKER_CONFIG /kaniko/.docker/

# We use 'RUN' instead of 'ADD' here due to odd caching issues where 'ADD' would still
# download S2I, then check that it hasn't changed before accepting it was cached.
# 'RUN' instead caches based on text contents.
RUN mkdir /s2i && \
    wget -O s2i.tar.gz https://github.com/openshift/source-to-image/releases/download/v1.3.1/source-to-image-v1.3.1-a5a77147-linux-amd64.tar.gz && \
    tar -xvf s2i.tar.gz -C /s2i && \
    rm -rf s2i.tar.gz

COPY package*.json ./
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]