FROM node:22-alpine as installer

RUN apk add --no-cache libc6-compat ca-certificates
RUN apk update

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/cache/npm npm install --cache=/cache/npm

COPY . .

EXPOSE 3001
EXPOSE 9229
CMD [ "npm", "run", "dev" ]