FROM python:3.13.1-bullseye AS sphinx-docs

RUN apt update && apt install -y pandoc

WORKDIR /app/docs

COPY docs .

RUN pip install bailo -r requirements.txt

RUN make dirhtml

FROM node:23.4.0-alpine AS installer

RUN apk add --no-cache libc6-compat ca-certificates
RUN apk update

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/cache/npm npm install --cache=/cache/npm

COPY . .
COPY --from=sphinx-docs /app/docs/python-docs python-docs

EXPOSE 3001
EXPOSE 9229
CMD [ "npm", "run", "dev" ]