[build-system]
requires = ["flit_core >=4.0,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "bailo"
authors = []
description = "Simplifies interacting with Bailo programmatically"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "requests>=2.26",
    "semantic-version>=2.4",
    "tqdm>=4.40",
]

[project.optional-dependencies]
mlflow = [
    "mlflow-skinny>=3",
]

[project.urls]
Documentation = "https://github.com/gchq/bailo/tree/main#readme"
Source = "https://github.com/gchq/bailo"
Tracker = "https://github.com/gchq/bailo/issues"
Changelog = "https://github.com/gchq/Bailo/blob/main/lib/python/CHANGELOG.md"

[dependency-groups]
test = [
    "pre-commit>=4",
    "pytest>=9",
    "pytest-cov>=7",
    "pytest-github-actions-annotate-failures>=0.4",
    "pytest-mock>=3",
    "requests-mock>=1",
    "ruff>=0.16",
]

[tool.flit.module]
name = "bailo"

[tool.coverage.run]
branch = true

[tool.coverage.report]
fail_under = 100

[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
]
venv = "env310"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src" }
]

[tool.pytest.ini_options]
addopts = "--cov-report xml:coverage.xml --cov src --cov-fail-under 0 --cov-append -m 'not (integration or mlflow)'"
pythonpath = [
  "src"
]
testpaths = "tests"
junit_family = "xunit2"
markers = [
    "integration: marks as integration test",
    "mlflow: marks as mlflow integration test",
]
