---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bailo-eks
  region: <region>
  version: <""> # k8s version; example "1.34"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: bailo-node
    instanceType: m5.xlarge
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeType: gp3
    volumeSize: 500
    volumeEncrypted: true
