from .catboost import catboost_bundler, catboost_loader, catboost_template
from .fastai import fastai_bundler, fastai_loader, fastai_template
from .gluon import gluon_bundler, gluon_loader, gluon_template
from .h2o import h2o_bundler, h2o_loader, h2o_template
from .keras import keras_bundler, keras_loader, keras_template
from .lightgbm import lightgbm_bundler, lightgbm_loader, lightgbm_template
from .onnx import onnx_bundler, onnx_loader, onnx_template
from .prophet import prophet_bundler, prophet_loader, prophet_template
from .pytorch import pytorch_bundler, pytorch_loader, pytorch_template
from .sklearn import sklearn_bundler, sklearn_loader, sklearn_template
from .spacy import spacy_bundler, spacy_loader, spacy_template
from .spark import spark_bundler, spark_loader, spark_template
from .statsmodels import statsmodels_bundler, statsmodels_loader, statsmodels_template
from .tensorflow import tensorflow_bundler, tensorflow_loader, tensorflow_template
from .xgboost import xgboost_bundler, xgboost_loader, xgboost_template
