---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bailo.fullname" . }}-registry
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      {{- if .Values.registry.serviceAccount }}
      serviceAccountName: {{ .Values.registry.serviceAccount }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "bailo.fullname" . }}-registry
        image: {{ .Values.registry.repository }}:{{ .Values.registry.tag }}
        resources:
          requests:
            cpu: 250m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 1000Mi
        ports:
          - name: http
            containerPort: {{ .Values.registry.port }}
            protocol: TCP
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.certFile }}
        - name: REGISTRY_HTTP_TLS_KEY
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.keyFile }}
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-minio
              key: root-user
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-minio
              key: root-password
        - name: REGISTRY_AUTH
          value: "token"
        - name: REGISTRY_AUTH_TOKEN_REALM
          #value: "https://{{ .Values.route.appPublicRoute }}/api/v1/registry_auth"
          value: 'http://{{ include "bailo.fullname" . }}-backend:{{ .Values.service.backendPort}}/api/v1/registry_auth'
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "RegistryAuth"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "RegistryIssuer"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.certFile }}
        - name: REGISTRY_AUTH_TOKEN_JWKS
          value: {{ .Values.registry.certDir }}/{{ .Values.registry.jwksFile }}
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "bailo.fullname" . }}-registry
              key: http-secret
        volumeMounts:
        - name: config-map-vol
          mountPath: /etc/distribution/config.yml
          subPath: config.yml
        - name: certs
          mountPath: {{ .Values.registry.certDir }}
      volumes:
      - name: config-map-vol
        configMap:
          name: {{ include "bailo.fullname" . }}-registry
          items:
          - key: registry.conf
            path: config.yml
      - name: certs
        secret:
          secretName: {{ include "bailo.fullname" . }}-certs
          items:
            - key: {{ .Values.nginxcert.cert }}
              path: {{ .Values.registry.certFile }}
            - key: {{ .Values.nginxcert.key }}
              path: {{ .Values.registry.keyFile }}
            - key: {{ .Values.registry.jwksFile }}
              path: {{ .Values.registry.jwksFile }}
