---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bailo.fullname" . }}-config
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
data:
  production.cjs: |
    module.exports = {{ tpl (.Files.Get "config/production.yaml") . | fromYaml | toPrettyJson | nindent 6 }}

  custom-environment-variables.cjs: |
    module.exports = {{ tpl (.Files.Get "config/environment.yaml") . | fromYaml | toPrettyJson | nindent 6 }}
